import { Link } from "wouter";
import { LegalPage, Section } from "@/components/LegalPage";

export default function Terms() {
  return (
    <LegalPage title="Terms of Service" updated="September 7, 2026">
      <Section title="The short version">
        <p>
          ClearPath HVAC is a diagnostic tool that maps your business's Profit &amp; Loss
          statement onto the ClearPath Insight Framework and shows you how it compares to
          benchmarks for businesses your size. It's meant to give you a clear, plain-English read
          on where your business stands — it is not tax, legal, financial, or accounting advice,
          and you're responsible for the data you upload and the decisions you make from what you
          see here.
        </p>
      </Section>

      <Section title="What the service is">
        <p>
          ClearPath HVAC lets you upload a P&amp;L export, review and correct how its line
          items are sorted into the ClearPath Insight Framework's categories, and view a
          scorecard and reports comparing your business to benchmark ranges for your revenue
          tier. It is an educational and diagnostic tool, not a substitute for advice from a
          qualified tax professional, accountant, or attorney who knows your specific situation.
          Nothing generated by this tool — categorizations, benchmark comparisons, tier
          placements, or narrative explanations — should be relied on as tax, legal, financial,
          or accounting advice.
        </p>
      </Section>

      <Section title="Your account">
        <p>
          You need a valid email address to sign in; access is passwordless, by a one-time link
          sent to that address. You're responsible for anything that happens under your account,
          and for using an email address you control. Accounts are for a single business or
          individual's own use — do not share sign-in access with people outside your
          organization without our agreement.
        </p>
      </Section>

      <Section title="Your data">
        <p>
          You represent that you have the right to upload the financial data you provide, and
          that doing so doesn't violate any other party's rights or any law that applies to you.
          You retain ownership of the data you upload; we use it only to provide the service to
          you, as described in our{" "}
          <Link href="/privacy" className="text-blue-600 hover:underline dark:text-blue-400">
            Privacy Policy
          </Link>
          . Data you upload is stored indefinitely by default, with a self-serve option in{" "}
          <Link href="/settings" className="text-blue-600 hover:underline dark:text-blue-400">
            Account settings
          </Link>{" "}
          to delete your financial data at any time, per the Privacy Policy above.
        </p>
      </Section>

      <Section title="Acceptable use">
        <p>
          Don't use ClearPath HVAC to upload data you don't have the right to use, to attempt
          to access another account's data, to interfere with the service's operation, or to
          reverse-engineer or resell the tool itself. We may suspend or terminate access for use
          that violates these Terms.
        </p>
      </Section>

      <Section title="No warranty">
        <p>
          ClearPath HVAC is provided "as is." The ClearPath Insight Framework's benchmarks and
          categorizations are general guidance, not tailored professional advice, and we make no
          guarantee that the tool's outputs are complete, accurate, or fit for any particular
          purpose — including where a PDF or CSV export doesn't parse the way you expect, or
          where a line item is categorized in a way you disagree with (you can always correct
          these). Review your own reports before relying on them.
        </p>
      </Section>

      <Section title="Limitation of liability">
        <p>
          To the maximum extent permitted by law, Online Tax Solutions Group LLC (dba Tax Sherpa)
          is not liable for any indirect, incidental, or consequential damages arising from your
          use of ClearPath HVAC, including decisions made based on its reports. Our total
          liability for any claim relating to the service is limited to the amount, if any, you
          paid us for it in the twelve months before the claim arose.
        </p>
      </Section>

      <Section title="Changes to the service or these Terms">
        <p>
          We may update these Terms, or change, suspend, or discontinue features of the service,
          at any time. The "Last updated" date above reflects the most recent revision to these
          Terms.
        </p>
      </Section>

      <Section title="Governing law">
        <p>
          These Terms are governed by the laws of the State of Georgia, without regard to its
          conflict-of-law principles.
        </p>
      </Section>

      <Section title="Who we are">
        <p>
          ClearPath HVAC is operated by <strong>Online Tax Solutions Group LLC</strong>, doing
          business as Tax Sherpa, 2302 Parklake Dr NE, Ste 675, Atlanta, GA 30345.
        </p>
      </Section>

      <Section title="Contact us">
        <p>
          Questions about these Terms can be directed to{" "}
          <a href="mailto:office@taxsherpa.com" className="text-blue-600 hover:underline dark:text-blue-400">
            office@taxsherpa.com
          </a>{" "}
          or by mail at the address above.
        </p>
      </Section>
    </LegalPage>
  );
}
